### ISSUE TITLE
Define report schema using Yamale

### ISSUE THREAD

**Issue by baijum** [redhat-certification/chart-verifier#100]
Ref. https://github.com/23andMe/Yamale

**Comment by baijum** [comment]
chart-testing uses it: https://github.com/helm/chart-testing#prerequisites

**Comment by mmulholla** [comment]
What are the benefits over our current yaml schema?

**Comment by baijum** [comment]
YAML is configuration format. But the schema of our data structure is not defined yet.  The definition exist in Go, but that's not really portable.

**Comment by komish** [comment]
@mmulholla I think we can probably **close** this as **out-of-scope** for now.
