### ISSUE TITLE
Workflow to publish images to quay using tag "dev" and not "latest" 

### ISSUE THREAD

**Issue by mmulholla** [redhat-certification/chart-verifier#112]
"latest" image will be used for GA and as such should not include further development. 
Publish to latest will need to be a manual check.

**Comment by isutton** [comment]
I've adjusted quay.io to publish images using the branch name as tag, and not publish a "latest" tag.

The configuration can be found [here](https://quay.io/repository/redhat-certification/chart-verifier?tab=builds), at the bottom of the page. In the case you don't have access to the repository in quay.io, please let either @isutton, @pedjak or @baijum know as we currently are the organization admins.

**Comment by mmulholla** [comment]
@isutton my quay user name is mmulholl

**Comment by isutton** [comment]
@mmulholla I've added you as admin in the redhat-certification org in quay.io.
