### ISSUE TITLE
Provide script to simplify running of  podman/docker commands

### ISSUE THREAD

**Issue by mmulholla** [redhat-certification/chart-verifier#113]
As part of release publish a script which enables a partner to run the chart verifier docker image without having to use the full podman/docker command.

**Comment by isutton** [comment]
The script should be along the lines of the following (tested locally
against a CRC cluster):

``` text
  docker run --rm -i									\
	 -e KUBECONFIG=/.kube/config						\
	 -v "${HOME}/.kube":/.kube							\
	 "quay.io/redhat-certification/chart-verifier:main" \
	 verify												\
	 https://dperaza4dustbit.github.io/helm-chart/psql-service-0.1.7.tgz
```

The `--kubeconfig` flag is available but has an issue tracked in #116.
