### ISSUE TITLE
Improve reason output when chart-testing fails

### ISSUE THREAD

**Issue by mmulholla** [redhat-certification/chart-verifier#114]
For example, current reason when no OC cluster is available is: 

Error waiting for process: exit status 1

Need to make sure error message provides a good indication of the underlying problem.

**Comment by mmulholla** [comment]
IBM were seeing this message today and were complaining it did not tell them anything. They were running the quay image using docker. 

When David ran their chart he saw the same message and difficult to know what the problem was. David then ran the same chart but using the command line version and this came out before the report:

```
Error: execution error at (ibm-object-storage-plugin/templates/flex-driver-sa.yaml:3:61): License must be accepted by setting license key to true
Deleting release 'ibm-object-storage-plugin-mng7o4fjcq'...
Error: uninstall: Release not loaded: ibm-object-storage-plugin-mng7o4fjcq: release: not found
Error deleting Helm release: Error waiting for process: exit status 1
```

Suddenly we had something to work with and David found the issue.

**Comment by isutton** [comment]
The output of external commands such as `helm` and `kubectl` which are
executed during the `chart-testing` check was being streamed to
Stdout, the same destination the report is streamed to and has been
silenced in #106:

	func (h Helm) Test(namespace string, release string) error {
		_, err := h.RunProcessAndCaptureOutput("helm", "test", release, "--namespace", namespace, h.extraArgs)
		return err
	}

	func (h Helm) DeleteRelease(namespace string, release string) {
		_, _ = h.RunProcessAndCaptureOutput("helm", "uninstall", release, "--namespace", namespace, h.extraArgs)
	}

It is likely the output should be captured together with an error, if
one is produced, and propagated to user.
