### ISSUE TITLE
verify's kubeconfig flag doesn't work

### ISSUE THREAD

**Issue by isutton** [redhat-certification/chart-verifier#116]
While running `chart-verifier` from within a container, I've found that while the following works:

``` text
  docker run --rm -i \
	 -e KUBECONFIG=/.kube/config \
	 -v "${HOME}/.kube":/.kube \
	 "quay.io/redhat-certification/chart-verifier:main" \
	 verify \
	 https://dperaza4dustbit.github.io/helm-chart/psql-service-0.1.7.tgz 2>&1

```

This doesn't:

``` text
  docker run --rm -i \
	 -v "${HOME}/.kube":/.kube \
	 "quay.io/redhat-certification/chart-verifier:main" \
	 verify --kubeconfig /.kube/config \
	 https://dperaza4dustbit.github.io/helm-chart/psql-service-0.1.7.tgz 2>&1
```

It is expected that using the `--kubeconfig` flag and setting the `KUBECONFIG` environment variable to behave similarly.

**Comment by komish** [comment]
@mmulholla I think this **can be closed**. Using 1.10.0, it seems like the file being passed in by --kubeconfig is referenced as I expect.
