### ISSUE TITLE
Report should be streamed to Stdout instead of Stderr

### ISSUE THREAD

**Issue by isutton** [redhat-certification/chart-verifier#123]
Currently the resulting report is being streamed to Stderr instead of
Stdout; this happens because `cobra.Command` assumes Stderr when a
default out writer hasn't been informed by the user, resulting in this
behavior.

It is expected that logs and other useful messages are streamed to
Stderr and the report streamed to Stdout when `chart-verifier` is
invoked like the following:

``` text
chart-verifier verify chart.tgz 2>log.txt 1>report.yaml
```

**Comment by komish** [comment]
Closing this as a duplicate if #117
