### ISSUE TITLE
Add tests which run the chart-verifer

### ISSUE THREAD

**Issue by mmulholla** [redhat-certification/chart-verifier#124]
Currently we do not have any tests which run the chart-verifier tool, all tests are go unit.

We need a set of test which ensure there are no regressions in tool functionality and all flags work as intended.

**Comment by isutton** [comment]
Although there are no tests executing the produced binary, tests in
`cmd/verify_test.go` are to the best of my knowledge equivalent from
the execution point of view, as it exercises command line switches and
expected outputs.

In other words, those are not unit tests but integration tests. For
example, the following test "should fail when chart does not exist and
argument is given":

``` go
	t.Run("Should fail when chart does not exist and argument is given", func(t *testing.T) {
		cmd := NewVerifyCmd(viper.New())
		outBuf := bytes.NewBufferString("")
		cmd.SetOut(outBuf)
		errBuf := bytes.NewBufferString("")
		cmd.SetErr(errBuf)

		cmd.SetArgs([]string{"../pkg/chartverifier/checks/chart-0.1.0-v3.non-existing.tgz"})

		err := cmd.Execute()
		require.Error(t, err)
		require.True(t, checks.IsChartNotFound(err))
	})
```

**Comment by mmulholla** [comment]
The existing tests are a bit limited:

- They only  test the -x and -e options so need a lot of tests added to cover all flags.
- They all use exactly the same chart so no variation in content processing.
- No test checks the full report content. 
- No test for chart as source, chart as a URL.
- No test of the container image.

We may not need to fill all of the gaps but but would be good to have some tests which run the tool the same way as we recommend to our users.

**Comment by isutton** [comment]
Good discussion!

I'll comment inline below with some context:

> The existing tests are a bit limited:
> 
> * They only  test the -x and -e options so need a lot of tests added to cover all flags.

Yes; I've disclosed in the integration of chart-testing is that testing is required and didn't have tests for all the switches. Instead of tackling all at once, I opted to create an issue to track the switches as they are used (see #116).

> * They all use exactly the same chart so no variation in content processing.

Yes, since the intention of charts in that particular point is to exercise features, and not to validate for false positives or negatives.

> * No test checks the full report content.

We should be more vigilant next time, since it should've been introduced when the output format has been defined (see #75).

> * No test for chart as source, chart as a URL.

Indeed; should've been introduced quite early on, when LoadChartFromURL was introduced.

> * No test of the container image.
> 
> We may not need to fill all of the gaps but but would be good to have some tests which run the tool the same way as we recommend to our users.

That was the intention of `cmd/verify_test.go`, as it is the test for the command and not any supporting business logic (which live in `pkg/...`).

I've opted to keep the tests at this level is that `cobra`, as demonstrated before, offers all the facilities one requires to execute tests solely using the Go toolchain.

**Comment by mmulholla** [comment]
Agree we use verify_test ahead of actually running the docker image but I still want at least a sanity test which does, just to check it all still works. 

Another aspect of testing is to provision a cluster so we can test chart-testing on a PR - for this I guess we can take from the workflow we now have in the charts repo.  May also be cool, if possible, to have an option for the chart-verifier to provision a cluster to run the tests on, can even make sure the role is good . Would match my laziness :-).  Could we even do that for a partner?

"It probably should've been introduced when the output schema has been defined (see #75)." Darn you got me! Sad when in my last job I was writing test to verify a file matched to a schema

**Comment by isutton** [comment]
Martin Mulholland ***@***.***> writes:

> Agree we use verify_test ahead of actually running the docker image but I still want at least a sanity test which does,
> just to check it all still works.

This should be part of #122, which I'm currently working on.

> Another aspect of testing is to provision a cluster so we can test chart-testing on a PR - for this I guess we can take
> from the workflow we now have in the charts repo. May also be cool, if possible, to have an option for the chart-verifier
> to provision a cluster to run the tests on, can even make sure the role is good . Would match my laziness :-). Could we
> even do that for a partner?

Perhaps this would be part of the chart-verifier's GitHub action?

> "It probably should've been introduced when the output schema has been defined (see #75)." Darn you got me! Sad when in my
> last job I was writing test to verify a file matched to a schema

Heh, I didn't mean to be picky :-) I should've also added command tests
for the different chart retrieval methods, as I think I pointed out as
well.
