### ISSUE TITLE
Chart verifier error: Missing OpenShift version. "openshiftVersion" not found in 'oc version' output. And the 'openshift-version' flag has not set.

### ISSUE THREAD

**Issue by mmulholla** [redhat-certification/chart-verifier#129]
if you run chart verifier after  https://github.com/redhat-certification/chart-verifier/pull/115

and you run the verifer without oc installed:

```docker run -v $(pwd):/charts --rm quay.io/redhat-certification/chart-verifier:278be83 verify /charts/chart-0.1.0-v3.valid.tgz```

you get this, both running the command line and the docker image: 
```
Error: Missing OpenShift version. "openshiftVersion" not found in 'oc version' output. And the 'openshift-version' flag has not set.
Usage:
  chart-verifier verify <chart-uri> [flags]

Flags:
  -S, --chart-set strings           set values for the chart (can specify multiple or separate values with commas: key1=val1,key2=val2)
  -G, --chart-set-file strings      set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
  -X, --chart-set-string strings    set STRING values for the chart (can specify multiple or separate values with commas: key1=val1,key2=val2)
  -F, --chart-values strings        specify values in a YAML file or a URL (can specify multiple)
      --debug                       enable verbose output
  -x, --disable strings             all checks will be enabled except the informed ones
  -e, --enable strings              only the informed checks will be enabled
  -h, --help                        help for verify
      --kube-apiserver string       the address and the port for the Kubernetes API server
      --kube-as-group stringArray   group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --kube-as-user string         username to impersonate for the operation
      --kube-ca-file string         the certificate authority file for the Kubernetes API server connection
      --kube-context string         name of the kubeconfig context to use
      --kube-token string           bearer token used for authentication
      --kubeconfig string           path to the kubeconfig file
  -n, --namespace string            namespace scope for this request
  -V, --openshift-version string    version of OpenShift used in the cluster
  -o, --output string               the output format: default, json or yaml
      --registry-config string      path to the registry config file (default "/root/.config/helm/registry.json")
      --repository-cache string     path to the file containing cached repository indexes (default "/root/.cache/helm/repository")
      --repository-config string    path to the file containing repository names and URLs (default "/root/.config/helm/repositories.yaml")
  -s, --set strings                 overrides a configuration, e.g: dummy.ok=false
  -f, --set-values strings          specify application and check configuration values in a YAML file or a URL (can specify multiple)

Global Flags:
      --config string   config file (default is $HOME/.chart-verifier.yaml)

Missing OpenShift version. "openshiftVersion" not found in 'oc version' output. And the 'openshift-version' flag has not set.
```

**Comment by isutton** [comment]
Martin Mulholland ***@***.***> writes:

> if you run chart verifier after #115
>
> and you run the verifer with oc installed you get this, command line and docker image:
>
> docker run -v $(pwd):/charts --rm quay.io/redhat-certification/chart-verifier:278be83 verify
> /charts/chart-0.1.0-v3.valid.tgz
>
> you get this, command line and docker image:
>
> Error: Missing OpenShift version. "openshiftVersion" not found in 'oc version' output. And the 'openshift-version' flag has not set.

If you're either not logged into a cluster or logged with an
unprivileged account, it is deliberate: the OpenShift chart-verifier
requires a valid OpenShift version present in the report, and it can be
obtained only through a user associated with a valid role binding as
explained earlier by Baiju.

By default in CRC, when interacting with the cluster using the
`kubeadmin` user, `oc version` produces a value for the
`openshiftVersion` field whereas when no value is produced when the
`developer` user is used; in those situations, when chart-verifier can't
guess on it own, a valid value should be informed by the user, resulting
in the error you've witnessed.

To avoid this situation the field should be moved somewhere else, but at
this point there isn't anywhere to be stored. @pedjak suggested earlier
to augment the check result data type to include a map of values
together with the check result; such map could be used to present this
value close to where it matters--in this case, the chart-testing
check--although this would require some deliberation.

**Comment by baijum** [comment]
Looks like issue #130 is the same as this issue.

**Comment by mmulholla** [comment]
This is a big behavior change to introdiuce with no discussion just before GA and shows a big issue with our tests - it should have caused a failure. The checks should still run and the error come out at the end.

**Comment by baijum** [comment]
I created a PR #133 Let me know if that approach is going to work. From the PR description:
```
Add OpenShift version if chart-testing is enabled

* Users should be able to run a check that doesn't require a cluster.
  Ensure the OpenShift version is available if the chart-testing
  check is enabled.

* If the user inputs an OpenShift version that should be a valid
  SemVer version.
```

**Comment by mmulholla** [comment]
I  think the better solution is to have getting the oc.version to be part of the chart-testing check, if we fail to get the OpenShift version the check fails and the reason informs the user as to why.

**Comment by isutton** [comment]
> I think the better solution is to have getting the oc.version to be
> part of the chart-testing check, if we fail to get the OpenShift
> version the check fails and the reason informs the user as to why.

Yes, I agree with this. Specially because there are a multitude of
checks that require no OpenShift cluster available whatsoever, so I
think it makes sense to bind that information with the check that
actually produces it.

To be sure, are we stating that at least conceptually a new
key--`extra` for now--will be added to the check schema backed by a
`map[string]string` value (I don't believe that a
`map[string]interface{}` is required since the semantics of this field
is similar to Kubernetes annotations, although it is easier to lift
restrictions than implementing them) so checks can contribute some
values from the its perspective such as the reason for this PR, the
`openshiftVersion` field?

If so, I would expect the following in the case of the `chart-testing`
check:

``` yaml
- check: chart-testing
  outcome: PASS
  extra:
    openshiftVersion: "4.7.5"
```

Are we on the same page, @mmulholla?
