### ISSUE TITLE
Running IBM chart ibm-object-storage-plugin-2.0.8.tgz fails with License issue

### ISSUE THREAD

**Issue by dperaza4dustbit** [redhat-certification/chart-verifier#134]
We (@mmulholla and I) were working with one of the IBMers trying to run the chart verifier. This is the feedback she gave us:

1. Expose the error so that the user knows what is wrong with the chart testing in the local cluster.
2. Honor the license value in the rendered templates. See the error below with older version of chart verifier showing the errors:
3. Add more example runs that pass in the docs so that developers can compare with their environments. 

You can get their charts here: https://github.com/IBM/charts/blob/master/repo/ibm-helm/ibm-object-storage-plugin-2.0.8.tgz

dperaza@dperaza-mac Downloads % chart-verifier verify --chart-set license=true $HOME/Downloads/ibm-object-storage-plugin-2.0.8.tgz 2>&1
Error: execution error at (ibm-object-storage-plugin/templates/flex-driver-sa.yaml:3:61): License must be accepted by setting license key to true
Deleting release 'ibm-object-storage-plugin-mng7o4fjcq'...
Error: uninstall: Release not loaded: ibm-object-storage-plugin-mng7o4fjcq: release: not found
Error deleting Helm release: Error waiting for process: exit status 1
apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.0.0
        chart-uri: /Users/dperaza/Downloads/ibm-object-storage-plugin-2.0.8.tgz
        digest: sha256:71334727f9bf10ece92c8d79eebac55a4d78cd4b21b63f0a9555310207004591
        lastCertifiedTimestamp: "2021-05-24T16:24:00.879823-04:00"
        certifiedOpenShiftVersions: 4.7.5
    chart:
        name: ibm-object-storage-plugin
        home: ""
        sources: []
        version: 2.0.8
        description: |
            Chart for deploying ibmcloud object storage plugin.
            IBM Cloud Object Storage is persistent, highly available storage
            that you can mount to apps that run in a Kubernetes cluster by using
            the IBM Cloud Object Storage plug-in. The plug-in is a Kubernetes Flex-Volume plug-in
            that connects Cloud Object Storage buckets to pods in your cluster.
        keywords:
          - IKS
          - amd64
          - Storage
          - Commercial
          - Limited
          - Other
          - ROKS
          - ICP
        maintainers:
          - name: IBM
            email: contsto2@in.ibm.com
            url: ""
        icon: https://cache.globalcatalog.cloud.ibm.com/static/cache/2461-acb0d10a1725d783/images/uploaded/icons/object-storage.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 2.0.8
        deprecated: false
        annotations: {}
        kubeversion: '>=1.10.1-0'
        dependencies: []
        type: ""
    overrides: ""
results:
  - check: not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
  - check: chart-testing
    type: Mandatory
    outcome: FAIL
    reason: 'Error waiting for process: exit status 1'
  - check: has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
  - check: images-are-certified
    type: Mandatory
    outcome: PASS
    reason: |-
        Image is Red Hat certified : ibmcom/ibmcloud-object-storage-driver@sha256:e07cf3ff8d56663fc33d19f0294a0c3f969038695a1d98f60fb762cbb6324053
        Image is Red Hat certified : ibmcom/ibmcloud-object-storage-plugin@sha256:bddac7c558cea2379724360b6a1fe8a50779d093d87047e16c0f967e2c7224a0
  - check: is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version specified
  - check: helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful

**Comment by dperaza4dustbit** [comment]
If I change the values file directly to have license=true then I get all passing se below. Definitely we are not overwriting the value in values file correctly.

dperaza@dperaza-mac Downloads % chart-verifier verify $HOME/Downloads/ibm-object-storage-plugin 2>&1          
NAME: ibm-object-storage-plugin-bq2ff4g52p
LAST DEPLOYED: Mon May 24 16:48:40 2021
NAMESPACE: davptest
STATUS: deployed
REVISION: 1
NOTES:
Thank you for installing: ibm-object-storage-plugin.   Your release is named: ibm-object-storage-plugin-bq2ff4g52p

1. Verify that the storage classes are created successfully:

   $ kubectl get storageclass | grep 'ibmc-s3fs'

2. Verify that plugin pods are in "Running" state:

   $ kubectl get pods -n davptest -o wide | grep object

   The installation is successful when you see one `ibmcloud-object-storage-plugin` pod and one or more `ibmcloud-object-storage-driver` pods.
   The number of `ibmcloud-object-storage-driver` pods equals the number of worker nodes in your cluster. All pods must be in a `Running` state
   for the plug-in to function properly. If the pods fail, run `kubectl describe pod -n davptest <pod_name>`
   to find the root cause for the failure.
deployment "ibmcloud-object-storage-plugin" successfully rolled out
NAME: ibm-object-storage-plugin-bq2ff4g52p
LAST DEPLOYED: Mon May 24 16:48:40 2021
NAMESPACE: davptest
STATUS: deployed
REVISION: 1
TEST SUITE:     ibmcloud-object-storage-driver-test
Last Started:   Mon May 24 16:49:59 2021
Last Completed: Mon May 24 16:54:59 2021
Phase:          Succeeded
NOTES:
Thank you for installing: ibm-object-storage-plugin.   Your release is named: ibm-object-storage-plugin-bq2ff4g52p

1. Verify that the storage classes are created successfully:

   $ kubectl get storageclass | grep 'ibmc-s3fs'

2. Verify that plugin pods are in "Running" state:

   $ kubectl get pods -n davptest -o wide | grep object

   The installation is successful when you see one `ibmcloud-object-storage-plugin` pod and one or more `ibmcloud-object-storage-driver` pods.
   The number of `ibmcloud-object-storage-driver` pods equals the number of worker nodes in your cluster. All pods must be in a `Running` state
   for the plug-in to function properly. If the pods fail, run `kubectl describe pod -n davptest <pod_name>`
   to find the root cause for the failure.
Deleting release 'ibm-object-storage-plugin-bq2ff4g52p'...
release "ibm-object-storage-plugin-bq2ff4g52p" uninstalled
apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.0.0
        chart-uri: /Users/dperaza/Downloads/ibm-object-storage-plugin
        digest: sha256:30fc28195ad9d9f3c8d8e62ed24e43a014c16eaa9dfd40f4b379aa081aaf6bbb
        lastCertifiedTimestamp: "2021-05-24T16:55:04.810764-04:00"
        certifiedOpenShiftVersions: 4.7.5
    chart:
        name: ibm-object-storage-plugin
        home: ""
        sources: []
        version: 2.0.8
        description: |
            Chart for deploying ibmcloud object storage plugin.
            IBM Cloud Object Storage is persistent, highly available storage
            that you can mount to apps that run in a Kubernetes cluster by using
            the IBM Cloud Object Storage plug-in. The plug-in is a Kubernetes Flex-Volume plug-in
            that connects Cloud Object Storage buckets to pods in your cluster.
        keywords:
          - IKS
          - amd64
          - Storage
          - Commercial
          - Limited
          - Other
          - ROKS
          - ICP
        maintainers:
          - name: IBM
            email: contsto2@in.ibm.com
            url: ""
        icon: https://cache.globalcatalog.cloud.ibm.com/static/cache/2461-acb0d10a1725d783/images/uploaded/icons/object-storage.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 2.0.8
        deprecated: false
        annotations: {}
        kubeversion: '>=1.10.1-0'
        dependencies: []
        type: ""
    overrides: ""
results:
  - check: contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version specified
  - check: not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
  - check: images-are-certified
    type: Mandatory
    outcome: PASS
    reason: |-
        Image is Red Hat certified : ibmcom/ibmcloud-object-storage-driver@sha256:e07cf3ff8d56663fc33d19f0294a0c3f969038695a1d98f60fb762cbb6324053
        Image is Red Hat certified : ibmcom/ibmcloud-object-storage-plugin@sha256:bddac7c558cea2379724360b6a1fe8a50779d093d87047e16c0f967e2c7224a0
  - check: chart-testing
    type: Mandatory
    outcome: PASS
    reason: Chart tests have passed
  - check: has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
  - check: helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful

dperaza@dperaza-mac Downloads %

**Comment by dperaza4dustbit** [comment]
More info... from the container it fails like this

dperaza@dperaza-mac Downloads % docker run --rm -i \                                                
          -e KUBECONFIG=/.kube/config \
          -v "${HOME}/.kube":/.kube \
          "quay.io/redhat-certification/chart-verifier:latest" \
          verify \
          --kube-context kubeadmin/api-crc-testing:6443 \
         /.kube/ibm-object-storage-plugin 2>&1
apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.0.0
        chart-uri: /.kube/ibm-object-storage-plugin
        digest: sha256:30fc28195ad9d9f3c8d8e62ed24e43a014c16eaa9dfd40f4b379aa081aaf6bbb
        lastCertifiedTimestamp: "2021-05-24T22:00:42.948384+00:00"
        certifiedOpenShiftVersions: 4.7.5
    chart:
        name: ibm-object-storage-plugin
        home: ""
        sources: []
        version: 2.0.8
        description: |
            Chart for deploying ibmcloud object storage plugin.
            IBM Cloud Object Storage is persistent, highly available storage
            that you can mount to apps that run in a Kubernetes cluster by using
            the IBM Cloud Object Storage plug-in. The plug-in is a Kubernetes Flex-Volume plug-in
            that connects Cloud Object Storage buckets to pods in your cluster.
        keywords:
          - IKS
          - amd64
          - Storage
          - Commercial
          - Limited
          - Other
          - ROKS
          - ICP
        maintainers:
          - name: IBM
            email: contsto2@in.ibm.com
            url: ""
        icon: https://cache.globalcatalog.cloud.ibm.com/static/cache/2461-acb0d10a1725d783/images/uploaded/icons/object-storage.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 2.0.8
        deprecated: false
        annotations: {}
        kubeversion: '>=1.10.1-0'
        dependencies: []
        type: ""
    overrides: ""
results:
  - check: has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version specified
  - check: chart-testing
    type: Mandatory
    outcome: FAIL
    reason: 'Error running process: exit status 1'
  - check: is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
  - check: helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
  - check: images-are-certified
    type: Mandatory
    outcome: PASS
    reason: |-
        Image is Red Hat certified : ibmcom/ibmcloud-object-storage-driver@sha256:e07cf3ff8d56663fc33d19f0294a0c3f969038695a1d98f60fb762cbb6324053
        Image is Red Hat certified : ibmcom/ibmcloud-object-storage-plugin@sha256:bddac7c558cea2379724360b6a1fe8a50779d093d87047e16c0f967e2c7224a0


when you do a describe on the failing test pod you will see this:

Warning  Failed     61m (x8 over 62m)   kubelet            Error: failed to mkdir /usr/libexec/kubernetes: mkdir /usr/libexec/kubernetes: read-only file system

**Comment by isutton** [comment]
> dperaza@dperaza-mac Downloads % chart-verifier verify --chart-set
> license=true $HOME/Downloads/ibm-object-storage-plugin-2.0.8.tgz 2>&1

I've done some digging and noticed that the `chart-testing` check
doesn't use the flags provided by the user:

	// Use anonymous function. Otherwise deferred calls would pile up
	// and be executed in reverse order after the loop.
	fun := func() error {
		namespace, release, releaseSelector, cleanup := generateInstallConfig(cfg, chrt, helm, kubectl)
		defer cleanup()

		if err := helm.InstallWithValues(chrt.Path(), valuesFile, namespace, release); err != nil {
			return err
		}
		return testRelease(helm, kubectl, release, namespace, releaseSelector, false)
	}

In contrast, the `helm-lint` check does make use of it:

	linter := lint.All(p, opts.Values, "default", false)

Our `helm.InstallWithValues` implementation discards `helm` and
`kubectl` outputs which were being streamed to Stdout, conflicting
with the report's default destination, so it should be safe to change
it to fulfill our requirements; I've brought this to attention because
this method is the topic of #114 as well, and work should be
coordinated.

**Comment by dperaza4dustbit** [comment]
Any feedback on why the chart verifier worked directly using binary vs using docker image? Remember she is using docker image path.

**Comment by dperaza4dustbit** [comment]
Maybe is bacause I used a previous version of binary, can you try to get her charts working through docker image to make sure it will work the same for her?

**Comment by dperaza4dustbit** [comment]
oh... I think is because the chart is being passed in the mounted volume and we can only do reads there?
