### ISSUE TITLE
[docs] KUBECONFIG file path should be volume mounted

### ISSUE THREAD

**Issue by baijum** [redhat-certification/chart-verifier#152]
Update documentation with these examples:
`-v ${HOME}/.kube/config:/kubeconfig:z -e KUBECONFIG=/kubeconfig`

**Comment by komish** [comment]
Copying the verbiage from #151 which I believe has the same goal.

> When running chart-verifier through docker/podman, the :z option should be documented as a note in the documentation to overcome the SELinux issue described here:
https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label

**Comment by komish** [comment]
This needs to be addressed here: https://github.com/redhat-certification/chart-verifier/issues/152
