### ISSUE TITLE
Upgrade to Go 1.16

### ISSUE THREAD

**Issue by baijum** [redhat-certification/chart-verifier#22]
Go 1.16 has the `embed` module which will be useful to implement #19

https://golang.org/pkg/embed/

**Comment by komish** [comment]
It seems this issue can be closed. The go.mod already points to [1.17](https://github.com/redhat-certification/chart-verifier/blob/main/go.mod#L3).

cc @mmulholla -- Good to **close as resolved**.

**Comment by mmulholla** [comment]
Yes, this is done.
