### ISSUE TITLE
Please add support for reports in Junit format

### ISSUE THREAD

**Issue by betoredhat** [redhat-certification/chart-verifier#232]
Hello team, 

Could support for reports in Junit format be added to the tool?

Thanks in advance!

**Comment by komish** [comment]
@betoredhat we can look into adding this as an additional report format.

**Comment by mgoerens** [comment]
@komish Can you confirm this is for the output of the `chart-verifier verify` command ? not `chart-verifier report`

**Comment by komish** [comment]
@mgoerens Yep, I would say the report.yaml (which is the output of `chart-verifier verify`) is what's in scope here.

I'm looking for this report.xml file to be generated in addition to report.yaml if the user requests it. By default, I believe chart-verifier spits the report.yaml to stdout, not a file. I do not expect the JUnit XML report to go to stdout as well. I expect it to be written out to a file if the user requests it.
