### ISSUE TITLE
Missing tags from repositories with many tags

### ISSUE THREAD

**Issue by ebaron** [redhat-certification/chart-verifier#259]
I have a test that uses the `ubi8/ubi` image. I've tried with both `latest` and `8.5`, but in both cases I get the result:
`
Image is not Red Hat certified : registry.access.redhat.com/ubi8/ubi:8.5 : Tag 8.5 not found. Found : 8.0-122, 8.0-122, 8.0-122, 8.0-122, 8.0-126, 8.0-126, 8.0-126, 8.0-126, 8.0-129, 8.0-129, 8.0-129, 8.0-129, 8.0-154, 8.0-154, 8.0-154, 8.0-154, 8.0-199, 8.0-199, 8.0-199, 8.0-199, 8.0, 8.0-208, 8.0, 8.0-208, 8.0, 8.0-208, 8.0, 8.0-208, 8.1-277, 8.1-277, 8.1-277, 8.1-277, 8.1-328, 8.1-328, 8.1-328, 8.1-328, 8.1-397, 8.1-397, 8.1-397, 8.1-397, 8.1-406, 8.1-406, 8.1-406, 8.1-406, 8.1, 8.1-408, 8.1, 8.1-408, 8.1, 8.1-408, 8.1, 8.1-408, 8.2-265, 8.2-265, 8.2-265, 8.2-265, 8.2-299, 8.2-299, 8.2-299, 8.2-299, 8.2-299.1592810498, 8.2-299.1592810498, 8.2-299.1592810498, 8.2-299.1592810498, 8.2-299.1594117625, 8.2-299.1594117625, 8.2-299.1594117625, 8.2-299.1594117625, 8.2, 8.2-347, 8.2, 8.2-347, 8.2, 8.2-347, 8.2, 8.2-347, 8.3-199, 8.3-199, 8.3-199, 8.3-199, 8.3-227, 8.3-227, 8.3-227, 8.3-227, 8.3-289, 8.3-289, 8.3-289, 8.3-289, 8.3-297, 8.3-297, 8.3-297, 8.3-297, 8.3, 8.3-297.1618432833, 8.3, 8.3-297.1618432833, 8.3, 8.3-297.1618432833, 8.3, 8.3-297.1618432833, 8.4-199, 8.4-199, 8.4-199, 8.4-199, 8.4-203, 8.4-203, 8.4-203, 8.4-203, 8.4-203.1622660121, 8.4-203.1622660121, 8.4-203.1622660121, 8.4-203.1622660121, 8.4-206, 8.4-206, 8.4-206, 8.4-206
`

Looking at the Pyxis endpoint, I see that there are 148 images, but only the first 100 are returned by default:
https://catalog.redhat.com/api/containers/v1/repositories/registry/registry.access.redhat.com/repository/ubi8/ubi/images

Passing the `page=1` argument, I see the remaining 48 images, including those with the `8.5` and `latest` tags:
https://catalog.redhat.com/api/containers/v1/repositories/registry/registry.access.redhat.com/repository/ubi8/ubi/images?page=1

**Comment by komish** [comment]
Closing this issue as it seems this is resolved, along with additional issues as noted in the PR.
