### ISSUE TITLE
Non zero code should be returned for failed verifications

### ISSUE THREAD

**Issue by sabre1041** [redhat-certification/chart-verifier#26]
Currently, as long as a chart undergoes verification, regardless of the outcome, a return code of zero is recorded.

Failed verifications should return a non-zero code so that the tool can be more easily integrated into an automation process (eg: CI/CD)

**Comment by sbose78** [comment]
+1

**Comment by mmulholla** [comment]
The chart-verifier is not intended to decide whether or not a chart has passed certification it merely creates a report. It is up to the consumer of the report to decide whether or not the chart is good.  What may be of help is that we are adding a second command which can be used to get information about the report, including a results summary. Details are here:

https://github.com/redhat-certification/chart-verifier/blob/main/proposals/reports-on-reports.md

This should be ready in a matter of days.

**Comment by komish** [comment]
@mmulholla I'm seeing the `chart-verifier report` command exists, but I'm still not seeing a way to get a non-zero exit code from the that report built-in through that command.

The command does give us this workaround, which seems effective enough.

```
test -z $(chart-verifier report results report.yaml | jq -r .results.failed)
```

Do we want to keep this open for further resolution? Contextually, it would seem this is solved (if the redhat-actions reference PR from above is to be believed that this is no longer a blocker to them), but I don't want to jump to conclusions. I'm not familiar enough to know if existing workflows having already solved this, yet.
