### ISSUE TITLE
readme-contains-values-schema check not implemented

### ISSUE THREAD

**Issue by sabre1041** [redhat-certification/chart-verifier#27]
Documentation via the `README.md` indicate that the `readme-contains-values-schema` has been implemented, however this is not the case.

In addition, how was this check planned to validate the README of the chart?

**Comment by baijum** [comment]
There is a check with the name as `contains-values-schema`. This checks for the presence of the schema JSON file in the chart.

**Comment by sabre1041** [comment]
@baijum where is this located?

**Comment by baijum** [comment]
> @baijum where is this located?

Sorry, the feature is not documented. But you can see the code here: https://github.com/redhat-certification/chart-verifier/blob/0fd6cd6231d885059dcda7c76e71f99bc157beb1/pkg/chartverifier/checks/checks.go#L119
And test: https://github.com/redhat-certification/chart-verifier/blob/0fd6cd6231d885059dcda7c76e71f99bc157beb1/pkg/chartverifier/checks/checks_test.go#L130

I will work on updating the docs.
