### ISSUE TITLE
Add support for testing daemon and statefulsets

### ISSUE THREAD

**Issue by danielchristod** [redhat-certification/chart-verifier#286]
Hello,

Please add support for testing daemon and statefulsets on test releases.

On [this ](https://github.com/redhat-certification/chart-verifier/blob/ac429dd185bc67df81e0e924435c1e33e2323c67/internal/chartverifier/checks/charttesting.go#L223) line, chart-verifier waits only for Deployments, but if test runs against daemon and statefulsets, they are not guaranteed to be deployed when helm tests start.

Thank you!

**Comment by dcurran90** [comment]
here's a pull request with a possible implementation 
https://github.com/redhat-certification/chart-verifier/pull/405
