### ISSUE TITLE
Failed to certify images chart requires kubeVersion: >=1.21 which is incompatible with Kubernetes v1.20.0

### ISSUE THREAD

**Issue by imdad000** [redhat-certification/chart-verifier#296]
we have added kubeVersion: >=1.21 on Chart.YAML
but with chart verifier getting this Error
check: v1.0/images-are-certified
      type: Mandatory
      outcome: FAIL
      reason: 'Failed to certify images : Failed to get images, error running helm template : chart requires kubeVersion: >=1.21 which is incompatible with Kubernetes v1.20.0'

**Comment by imdad000** [comment]
https://stackoverflow.com/questions/74794746/helm-charts-on-ocp-developer-catalog-using-red-hat-repository-issues-with-check

**Comment by nikeshmi** [comment]
@mmulholla Can someone from the RH team look at this issue on priority as its blocking our push to the OpenShift developer catalog

**Comment by nikeshmi** [comment]
Can anyone in the team provide an update on this issue?

**Comment by mmulholla** [comment]
@nikeshmi  This looks an error from helm if you run ```helm template``` on the chart.  Would like to see how kubeVersion is specified in the chart.

**Comment by mmulholla** [comment]
@nikeshmi it should work if you upgrade helm to 3.11

**Comment by morstad** [comment]
chart verifier
```
Digest: sha256:1897b6d0fdc6c8f5dbf6ce2041501f262f3bdeea3469a0c4a7105ce49f3572b0
Status: Image is up to date for quay.io/redhat-certification/chart-verifier:latest
quay.io/redhat-certification/chart-verifier:latest
```

helm version
```
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.18.10"}
```

helm template works as expected 
```
helm template https://github.com/IBM/charts/blob/master/repo/ibm-helm/ibm-object-storage-plugin-2.2.10.tgz?raw=true --set license=true
---
# Source: ibm-object-storage-plugin/templates/flex-driver-sa.yaml
# ServiceAccount for ibmcloud-object-storage-drivertrue
apiVersion: v1
kind: ServiceAccount
metadata:
...
```

**Comment by mmulholla** [comment]
I figured out the issue, will have pull request ready soon.

**Comment by mmulholla** [comment]
@morstad I have a PR for a fix #315 

Once it gets reviewed, approved and merged there will be an image available with the fix with tag `main`. After that we can do a release to make it available with tag 'latest'. If you need things sooner or want to test there is an image with tag `martin` which i use for testing which included the fix.

**Comment by mmulholla** [comment]
@morstad there are now images 'main' and '0.1.0' available which include the fix.
Will work with the new certification team to do a release so latest gets updated, but hopefully you are unblocked now.

**Comment by morstad** [comment]
Thanks - team is testing.

**Comment by komish** [comment]
I believe [release 1.10.1](https://github.com/redhat-certification/chart-verifier/releases/tag/1.10.1) should have this change. I'll close this issue.
