### ISSUE TITLE
Chart digest generation is impacted if you run chart-verifier from within the same directory as the chart

### ISSUE THREAD

**Issue by komish** [redhat-certification/chart-verifier#316]
## What Happened

I noticed that chart-verifier was producing a report with `.metadata.tool.digests.chart` changing with every execution, despite pointing to the same location with no changes. 

When executing it, I was in the chart directory running `chart-verifier verify .`.

This was producing the `chartverifier/` directory which contained log files. With each iteration, a new log file would be produced in this directory.

These log files are getting picked up when the chart location is slurped up, and as a result, the sorted list of files contained in the chart was changing every execution, causing my calculated digest to change (ultimately failing certification as well).

## Detail

The code snippet of concern is here:

https://github.com/redhat-certification/chart-verifier/blob/main/internal/chartverifier/reportBuilder.go#L196. The `rawFiles` parameter contains all files in that directory so those are all taken into account when calculating the hash.

The resolution would probably either need to decipher what's necessary and what isn't.

## Version

v1.10.0

## Workaround

It would seem that running chart-verifier in a different directory should produce an accurate hash. I'm still testing this now.

**Comment by dcurran90** [comment]
looking into this. would you mind assigning to me @komish ?
