### ISSUE TITLE
Issues with Publishing Image : Reason Health Index must be A to publish

### ISSUE THREAD

**Issue by imdad000** [redhat-certification/chart-verifier#318]
<img width="820" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/25360732/225272366-fcdfc0ef-361a-42c8-8184-77ce17059c97.png">

We are not able to publish our images on our Container Image project(6410c31628db1f516b396655) on conect.redhat.com. The images cannot be published due to the health index 
showing up as 'Unknown' inspite of the certification test having passed. The images were submitted using the preflight tool referring to IBM Entitled Registry(cp.icr.io).
Because of the above issue the chart verifier check for "images-are-certified" is failing with the below error since its not able to locate the image registry/repository. Search url: https://catalog.redhat.com/api/containers/v1/repositories/registry/image-registry.openshift-image-registry.svc:5000/repository/default/b2bi/images, tag: , sha: sha256:a0e0cc1b5dcd744f787657642a52701edc93691dbe453d3b90097c29e7b535f4 '     
- Entry: '[INFO] [2023-March-13 9:3:29.152042718] : page: 0, page_size: 100, total: 0' This is blocking us from publishing our new helm chart version on OpenShift Developer Catalog.

**Comment by acornett21** [comment]
@imdad000 This repo is for the chart verification tool itself, if there are issue with the certification process itself, you should open a support case against the project in question. You can do this by logging into connect and going [here](https://connect.redhat.com/support/technology-partner/#/). Hope this helps!
