### ISSUE TITLE
Identify the source of the unused linting warning for setOverridesFlag

### ISSUE THREAD

**Issue by komish** [redhat-certification/chart-verifier#322]
In cmd/verify.go https://github.com/redhat-certification/chart-verifier/blob/main/cmd/verify.go#L47, the `setOverridesFlag` triggers golangci-lint because it's unused. 

We should verify that it's unused, try to find places where its use is intended but disconnected, and decide to either wire it in or remove it. Worth checking the commit where it was introduced, and any commits thereafter to see how it has been manipulated.

**Comment by dcurran90** [comment]
after some investigation it looks like [this](https://github.com/redhat-certification/chart-verifier/commit/3f00873be5e34fa1f5749b2eada90d3784fa57ba) is the commit which removed the references to the "setOverridesFlag" 
Seems as though it pretty much just replaces "setOverridesFlag" with "verifyOpts.values" and missed removing the initial reference
