### ISSUE TITLE
How will new rules be versioned?

### ISSUE THREAD

**Issue by tetchel** [redhat-certification/chart-verifier#33]
This is kind of in-line with my other issue https://github.com/redhat-certification/chart-verifier/issues/32 in that this project doesn't have any tags or releases yet. The Docker images are also only tagged with "latest" and "main" which will obviously keep rolling forward with new changes.

I fear that if I add this as a check to my chart's CI workflow and fix all the issues, then my workflow may suddenly start failing if a new default check is added to this project.

How will the verification rules be versioned to prevent this from happening? Are they built into the binary, or fetched at runtime?

**Comment by sbose78** [comment]
We should change this anyway, untagged images are risky :)

**Comment by baijum** [comment]
Another issue: Partners cannot report issues against a particular version as there is no tag for the chart-verifier.

**Comment by mmulholla** [comment]
we have not created a tag yet because they were a few issues in the verifier which are being fixed.  Hoping to create the tag by the end of this week.

**Comment by mmulholla** [comment]
The basic premise of new rules is that they will first be introduced as optional, so will not cause certification failures and we can set a date when they will move to mandatory. Once they become mandatory,  reports without or with failures in the new checks or with will result in failure.

**Comment by dperaza4dustbit** [comment]
Definitely need to support version for chart-verifier. Latest can be renamed to our 1.0.0. Once there is at least one chart in from partners we can only move minor versions for now (no braking changes, that pass all test against existing charts). While we don't support verifier version in report we cannot make a mayor version change. The mayor version is assumed to brake at least one of the certified charts and then partner will be notified to be certified at then next level of verifier. Think of verifier version as our spec version. This will all be document under this epic https://issues.redhat.com/browse/HELM-120 and the few stories to be added under that. There is also the concept of profile we are also entertaining. More on this coming up

**Comment by mmulholla** [comment]
we now have releases 1.0.0 and 1.0.1 in addition to a rolling main, latest is 1.0.1 and will always be the most recent release.

**Comment by tetchel** [comment]
great, I see there are tagged versions of the docker image too.

are the rules built into the binary, the docker image, or are they fetched at runtime?
