### ISSUE TITLE
add option to chart-verifier to skip clean up after chart testing has completed. 

### ISSUE THREAD

**Issue by wying3** [redhat-certification/chart-verifier#330]
we require to add option for the chart-verifier. This flag would allow the chart-verifier to skip clean up the CNFs after completing the helm chart test. With this new feature, we can initiate a sequent job for CNF testing without reinstalling the helm chart, providing a more efficient and streamlined testing process for full course of CNF certification

**Comment by komish** [comment]
Thanks for the report @wying3. We'll take a look at how plausible this is and get back to you if we're able to integrate this feature.

**Comment by dcurran90** [comment]
looking into feature.
will post a PR for review here soon
