### ISSUE TITLE
Enable integration with other chart verification system

### ISSUE THREAD

**Issue by jasperchui** [redhat-certification/chart-verifier#36]
Enable the ability for the chart-verifier to integrate with other linting tools.  ie. StackRox

**Comment by mmulholla** [comment]
StackRox kubelinter doc: https://www.stackrox.com/post/2021/02/what-is-kubelinter/
kubelinter go code: https://pkg.go.dev/golang.stackrox.io/kube-linter/pkg

You will see a list of the 19 checks (13 default) which they perform, need to decide which ones we want to use. Also do we want a single kubelinter check to cover all checks in the report or more granular?

Also kubelinter is intended as a command line tool and the go code uses Cobra as we do. As a result the go is not so much an api as an implementation similar to the chart verifier. This means the documentation is weak and it is probably unwise to for us to do anything other  than invoke the command through go.

**Comment by jasperchui** [comment]
Please note the [kube-linter](https://github.com/redhat-certification/chart-verifier/labels/kube-linter) label identifies a number of checks that we should evaluate as we proceed.
