### ISSUE TITLE
Add commit information to version output of chart-verifier

### ISSUE THREAD

**Issue by komish** [redhat-certification/chart-verifier#362]
This is a useful breadcrumb to identify exactly what commit was used to build a given version. Specifically useful for the dev release.

**Comment by mgoerens** [comment]
@komish Could you please assign this issue to me ?

**Comment by komish** [comment]
Done @mgoerens. At a minimum, I just want the commit used to build this to be injected at binary build time. Like what you might see from `git rev-parse head`. 

What may also be interesting is a modified for the `version` subcommand that spits this, as well as the version string out as a data blob. Something like `chart-verifier version --as-data` spitting out

```json
{ "version": "1.12.0", "commit": "aaaaaabbbbbbcccccc"}
```

The latter idea isn't a hard requirement. Thanks for taking a look!
