### ISSUE TITLE
Remove docker-related tests and docs

### ISSUE THREAD

**Issue by mgoerens** [redhat-certification/chart-verifier#378]
~There are multiple issues with the "test" part which makes this script not usable as-is:~
~- the chart used for testing has been moved to another location (easy fix)~
~- the verify command uses a -l flag which isn't supported anymore (easy fix)~
~- the verify command requires access to a Kubernetes cluster. Currently there is no way to provide Kubernetes credentials to the script (fixable, with some effort)~

~But before putting further effort into fixing the "test" part of this script, it appears to me like we don't need this script to be able to test a docker image anymore. The pipeline takes care of that in a next step (actually running some extensive tests). AFAICT this script is never called without the --build-only flag in our testing / release process and anyway would not work.~

~Hence suggesting to remove the "test" part of this script.~

See below

**Comment by mgoerens** [comment]
@komish Some time ago we talked about removing the docker tests completely. We can use this issue as a tracker.

The arguments in favor of removing the docker tests:
* Simplification
* We already test the container image with podman

Did I get this right ?

**Comment by komish** [comment]
@mgoerens 100% agree. I think we get sufficient coverage by testing just Podman as the runtime.
As far as what work goes into it, I think:
- Removing Docker-related code from our e2e tests (e.g. if we specify Docker as a test parameter in our feature definitions, we can remove them)
- Any code that requires talking to the Docker API can probably be removed as we probably don't need it
- Any documentation that specifies the docker CLI can probably be reworded.

**Comment by mgoerens** [comment]
> Any code that requires talking to the Docker API can probably be removed as we probably don't need it

You mean in the tests specifically, or do you foresee modifications to chart-verifier ?

**Comment by komish** [comment]
Just for tests. Chart Verifier should not be talking to the Docker API.
