### ISSUE TITLE
Generate a digest of Helm Chart 

### ISSUE THREAD

**Issue by jasperchui** [redhat-certification/chart-verifier#42]
Generate the digest of Helm Chart content

**Comment by mmulholla** [comment]
Create list of chart files in alphabetic order and create a sha from it. Include all subdirectories.
Sha added to report.

**Comment by mmulholla** [comment]
From discussion with Predrag the idea is to sort all files in the chart into alphabetic order and then generate a sha. Additionally as the tool will run in a container and have no mounted volume the chart will have be be in memory - is it possble to use the template if the template files are included in alphabetic order?

**Comment by mmulholla** [comment]
Fixed in https://github.com/redhat-certification/chart-verifier/pull/75
