### ISSUE TITLE
Add check for the existence of  NOTES.txt template in a given chart

### ISSUE THREAD

**Issue by zvigrinberg** [redhat-certification/chart-verifier#428]
In helm chart  that contains `NOTES.txt` template, it rendered and printed to the screen after helm install/upgrade command completed.

It's very recommended to have a NOTES.txt template in any chart, because in this way, we can supply for the user many interesting details and information about the deployment that helm install command just deployed, and how to use it, customize it , and even more.

obviously implementing this check is very  simple and straightforward.

More details of helm `NOTES.txt` template:

https://helm.sh/docs/chart_template_guide/notes_files/

**Comment by rocrisp** [comment]
Hi Zvi, Thank you for posting this issue. So Chart verifier doesn't care about NOTES.txt is in the chart. Are you seeing error? Or perhaps you want the chart owner to include NOTES.txt if not found when validating the helm chart.

**Comment by zvigrinberg** [comment]
> Hi Zvi, Thank you for posting this issue. So Chart verifier doesn't care about NOTES.txt is in the chart. Are you seeing error? Or perhaps you want the chart owner to include NOTES.txt if not found when validating the helm chart.

Hi @rocrisp 
It's not an error, just a recommendation to add this simple check as an improvement, to verify existence of NOTES.txt, and if not found, fail the check... it could be even an optional check, not mandatory , but this is up to you.
