### ISSUE TITLE
Enable users to run checks against the charts

### ISSUE THREAD

**Issue by jasperchui** [redhat-certification/chart-verifier#46]
Enable partners to run checks against a Helm Chart

Checks:
- Helm Chart Checks #47

Features:
- Ability to integrate with other Helm Chart Check providers #36 (ie. Stackrox, IBM cv)
- Ability to define which checks are mandatory, optional, experimental 

Outcome of the check:
- Digest of Helm Chart content (not sha of tarball) #42 
- OCP version used for performing the checks #43
- Outcome of all performed checks (passed/failed)

**Comment by mmulholla** [comment]
Closing as now combined with #47
