### ISSUE TITLE
Installing chart-verifier from openshift-tools-installer fails due to release asset being malformed

### ISSUE THREAD

**Issue by jessesimpson36** [redhat-certification/chart-verifier#463]
Hey all,

My company writes a CI pipeline that makes use of the chart-verifier, but lately our builds have been failing.

![2024-08-06-164336_grim](https://github.com/user-attachments/assets/7bb6a02a-24e7-4eb4-8339-04302d21067d)

The error reads:
```
Error: No chart-verifier file was found for amd64 linux .
```

I thought this was odd, so I went to the openshift-tools-installer code:

https://github.com/redhat-actions/openshift-tools-installer/blob/bee649bbedc67b5bfc2f2de4b19498e11c2e8775/src/installer/install.ts#L76-L95

It looks like it expects the release assets to be of a certain format. When I check the releases in this chart-verifier repo, I see that the asset for the latest release is 

![2024-08-06-164548_grim](https://github.com/user-attachments/assets/aac4736a-d667-4aee-a902-dedc8877869c)

`chart-verifier.tgz-1.13.6.tgz`

Could someone please rename this to 

`chart-verifier-1.13.6.tgz`   ?

**Comment by jessesimpson36** [comment]
Here is the path inside your github actions workflow that duplicates the tgz extension:

https://github.com/redhat-certification/chart-verifier/blob/203492b293c7e30aa0f384313b628ab58a336cb9/.github/workflows/release.yaml#L52

**Comment by jessesimpson36** [comment]
I opened a PR 
https://github.com/redhat-certification/chart-verifier/pull/464

that will hopefully address this issue.

**Comment by mgoerens** [comment]
Good catch. I've renamed the tarball in the latest release to `chart-verifier-1.13.6.tgz`, let me know if that fixes the issue for you.

**Comment by jessesimpson36** [comment]
Thanks for renaming it. For some reason I am still having my issue 
```
Error: No chart-verifier file was found for amd64 linux
```

But I think I'm on the right track, and am happy about the edit regardless.  I will update here if I learn anything more, but I might need to be searching for an issue in the openshift-tools-installer instead.

**Comment by komish** [comment]
Closing the loop on this - I addressed @jessesimpson36's subsequent concern - see https://github.com/redhat-certification/chart-verifier/pull/464#issuecomment-2273734253

**Comment by jessesimpson36** [comment]
I confirmed that the hotfix from your comment was enough to make my CI pipeline pass. Thanks again!

**Comment by komish** [comment]
This should be all sorted. Closing this out.
