### ISSUE TITLE
README update for GA

### ISSUE THREAD

**Issue by mmulholla** [redhat-certification/chart-verifier#59]
readme needs updating for GA, including (in no particular order):

- [x] purpose of the tool
- [x] tool errors : cause and actions,
- [x] what to do with the report (editing, signing, including in a PR).
- [x] details of report content.
- [x] how to download and run the docker container.
- [x] Verification with an OCP cluster.
- [x] How to submit issues and suggestions

**Comment by Preeticp** [comment]
Currently being tracked in the docs Jira board and worked on by @harshcasper

**Comment by Srivaralakshmi** [comment]
@Srivaralakshmi

**Comment by mmulholla** [comment]
all done
