### ISSUE TITLE
Verify that containers aren't running with elevated scc

### ISSUE THREAD

**Issue by sbose78** [redhat-certification/chart-verifier#62]
Ref https://www.openshift.com/blog/managing-sccs-in-openshift

The default is "restricted". User workloads ideally should work with "restricted". If not, we must discuss.

I'm not sure if there's a way to verify this with kube-linter.

**Comment by komish** [comment]
Closing this as the SCC and PSA model has changed a bit since this was created. If this is still relevant, it'll require new scoping and refinement.
