### ISSUE TITLE
Generate output in SARIF format

### ISSUE THREAD

**Issue by gorkem** [redhat-certification/chart-verifier#68]
Generate output in [SARIF](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=sarif) format instead of a custom JSON format. This allows the tool to be integrated easier with git providers like [GitHub](https://dzone.com/articles/how-to-get-nice-error-reports-using-sarif-in-githu) or [vscode](https://marketplace.visualstudio.com/items?itemName=MS-SarifVSCode.sarif-viewer)

There are libraries like [go-sarif](https://github.com/owenrumney/go-sarif) that can help with the implementation of it.

**Comment by komish** [comment]
@mmulholla For now, I'd think **this** can be closed as **out of scope**.
