### ISSUE TITLE
Create schema and check for Partner annotations

### ISSUE THREAD

**Issue by jasperchui** [redhat-certification/chart-verifier#71]
To capture partner annotations details create a schema to define expected values and a check to verify that the chart contains the requested data.

As of Apr 9, 2021: 
helm-chart.openshift.io/provider | name of chart provider (e.g. Red Hat), ready to be displayed in UI
helm-chart.openshift.io/name | human readable chart name, ready to be displayed in UI
helm-chart.openshift.io/supportURL | how users can contact support
helm-chart.openshift.io/archs | comma separated list of supported architectures (e.g. x86_64, s390x,...)

**Comment by mmulholla** [comment]
Done
