### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by mmulholla** [redhat-certification/chart-verifier#72]
As part of the release process we need to publish the verifier tool docker image and ensure the readme provides instruction of where to get it form and how to use it. 

For docs see: https://github.com/redhat-certification/chart-verifier/issues/59

**Comment by hickey** [comment]
Please prioritize this issue. Having a docker image of `chart-verifier` will allow the tool to be added to existing pipelines as just another job. That is preferable over having to compile the tool each time to add the report generation into a pipeline.

**Comment by isutton** [comment]
@hickey, an image is already available in quay.io:

	docker pull quay.io/redhat-certification/chart-verifier
	
You can see more information about the build [here in
quay.io](https://quay.io/repository/redhat-certification/chart-verifier).

**Comment by hickey** [comment]
Excellent!!! Thank you for the info.

**Comment by isutton** [comment]
> Excellent!!! Thank you for the info.

@hickey, were you able to reach the container image?

**Comment by komish** [comment]
@mmulholla Good to close here, I see images have been published for a while. Confirming that the release 1.10.0 (released today) also is available.

```
 ⤿ skopeo inspect docker://quay.io/redhat-certification/chart-verifier:1.10.0 | jq .Digest
"sha256:1897b6d0fdc6c8f5dbf6ce2041501f262f3bdeea3469a0c4a7105ce49f3572b0"
```

**Comment by mmulholla** [comment]
Closing.
