### ISSUE TITLE
Chart verifier and submission service process

### ISSUE THREAD

**Issue by mmulholla** [redhat-certification/chart-verifier#87]
We need a documented service process probably by GA. Conisderations:

- when we GA we should:
   -  create v.1.0.0 image in quay, create a release in git.
   - update the submission process to use this image
   - If we need to fix  a bug in the certifier we update this image - v.1.0.1? Submission process needs updating too?
      - we continue to accept reports generated with v.1.0.0
  - If we modify/add a test we provide a new image v.1.1.0 or V2.0.0
     - now reports submitted with older version are rejected? 
          - need a delay between updating the verifier and the submission process to use the updated verifier?
          - need to be able to accept two report versions at the same time?
  - The submission process is different from the verifier because the main branch is always live so development must be done in a dev branch 
  - updates to the submisson process cannot be tested in place (immediately live) 
  - no need to version numbers? Do we tag the dev branch at significant milestones?

**Comment by baijum** [comment]
* I have created an issue to chart-verifier tool version mismatch in the charts repo:  [Fail the build if an old version of chart-verifier is used to generate the report](https://issues.redhat.com/browse/HELM-162)
  * We need to give a heads-up to partners and community whenever we are changing the version with check related (not bugfixes)
  * Let's clarify these things at next meeting with Hugo & Stevan
* To support testing the submit process in another repository. I have avoided all hardings.
  * See these two commits:
    *  https://github.com/openshift-helm-charts/repo/commit/dd3d2d262bdd8346f884300ea7e8771d1d40651d
    *  https://github.com/openshift-helm-charts/repo/commit/d144432695f804973cef54f7a51916754ed51443
  * I am already testing this in another repository: https://github.com/miles2go/repo

**Comment by komish** [comment]
@mmulholla I think this is issue can probably **close**, as the project has released and this issue is quite old.
