### ISSUE TITLE
Digest calculation should respect .helmignore

### ISSUE THREAD

**Issue by baijum** [redhat-certification/chart-verifier#92]
From the [ .helmignore documentation](https://helm.sh/docs/chart_template_guide/helm_ignore_file/):

> The .helmignore file is used to specify files you don't want to include in your helm chart.
> 
> If this file exists, the helm package command will ignore all the files that match the pattern specified in the .helmignore file while packaging your application.
> 
> This can help in avoiding unnecessary or sensitive files or directories from being added in your helm chart.

If the user creates a report using the source and the tarball, the digest values are different. I think we can always produce the tarball and generate the report. This way, the digest will be consistent.

**Comment by mmulholla** [comment]
My position is you need to run the chart against the form of chart you submit, you cannot run it against the source and then submit a tarball and vice-versa. I put this in the README I updating:

```If the report is submitted with a chart it must be run against the chart as submitted. So, for example, if submitting a tarball, run the report against the tarball that will be submitted. This is important because the report will calculate and record a sha256 value for the chart. The submission process will then re-generate the sha256 value and the process will fail if the sha values do not match.```

**Comment by baijum** [comment]
I am fine with @mmulholla suggestion. I have updated my PR accordingly: https://github.com/openshift-helm-charts/repo/pull/58
